FROM node:20-alpine as build

WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .
RUN npm exec vite build

FROM nginx:stable-alpine
COPY --from=build /app/.svelte-kit /usr/share/nginx/html
COPY --from=build /app/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 4000
CMD [ "nginx", "-g", "daemon off;" ]
